#pragma once

#define MENU 0
#define PASILLO1 1 //Pasillo de tarjeta
#define LECTOR 2 
#define MANGUERA 3
#define MANGUERASINTARJETA 4
#define PASILLO2 5 //Pasillo parte tupper
#define TUPPERMICROCERRADO 6
#define MICROCERRADO 7
#define TUPPERMICROABIERTOCONPAPEL 8
#define MICROABIERTOCONPAPEL 9
#define TUPPERMICROABIERTOSINPAPEL 10
#define MICROABIERTOSINPAPEL 11
#define FINAL 12
#define LECTORFINAL 13
#define FINJUEGO 14

#define VIDEOPASILLOTUPPER 15
#define VIDEOTUPPERPASILLO 16
#define VIDEOESCALERAS 17
#define VIDEOVICTORIA 18
#define VIDEOMUERTE 19
